### ISSUE TITLE
on_draw / on_update inconsistency

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#2579]
https://discord.com/channels/458662222697070613/458662458198982676/1343259854336163861

https://discord.com/channels/458662222697070613/696054878593744946/1041610876718940181

Potential fix

* Deprecate one of draw_rate or update_rate (remove in 4.0)
* When `draw_rate == update_rate`, use a single timer for both

This means a single call to pyglet `clock.schedule_interval()` or equivalent. The issue is using two different pyglet event handlers, running two different intervals on the pyglet event loop. There is currently no guarantee exactly on update+draw is done per frame when `scheduled_interval` is caled twice.

![Image](https://github.com/user-attachments/assets/ec6fee95-34c9-4642-b3f1-9994fd40766e)

**Comment by DragonMoffon** [comment]
I disagree with this solution to the problem. Linking the two calls is walking backwards on good features. I do think we need to solve why the calls are being doubled incorrectly like this.

Rather than depreciating the two, I'd be down for letting the user set one of them to `None` or an explicit flag that links the two together.

I've also never seen this issue before in my own testing of draw and update ordering.

Even if they aren't rendered at this rate, higher update rates improve a lot and throwing that away is a waste.

**Comment by einarf** [comment]
I am actually suffering from this issue a lot I discovered. A temp fix is likely to use the old behavior when default settings like suggested. I agree that the root of the problem also needs fixing here.

BUT the problem is currently SO bad on some platforms I would say arcade is partially broken. It gets worse the lower framerates you have. Things are extremely choppy.

**Comment by eruvanos** [comment]
This might also explain some of my issues with a stuttering animation. The quick fix for equal frequency should be good.

**Comment by einarf** [comment]
Yes. It's pretty bad right now. We need at least a temp fix until this is sorted out.

**Comment by DragonMoffon** [comment]
With the merged fixes can this be closed?

**Comment by eruvanos** [comment]
Not yet, we have a quickfix for mac on the way: https://github.com/pythonarcade/arcade/pull/2606
and have to update to a new pyglet version, to remove it

**Comment by eschan145** [comment]
I'm getting an error that I believe is caused by this PR:

```
  File "C:\Users\1079235\test\src\__init__.py", line 116, in start
    run(1/69)

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\pyglet\app\__init__.py", line 79, in run
    event_loop.run(interval)

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\pyglet\app\base.py", line 164, in run
    timeout = self.idle()
              ^^^^^^^^^^^

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\pyglet\app\base.py", line 232, in idle
    self.clock.call_scheduled_functions(dt)

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\pyglet\clock.py", line 217, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\arcade\application.py", line 538, in _dispatch_frame
    self.draw(self._accumulated_draw_time)

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\pyglet\window\__init__.py", line 697, in draw
    self.switch_to()

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\arcade\application.py", line 1088, in switch_to
    super().switch_to()  # type: ignore # Window typed at runtime
    ^^^^^^^^^^^^^^^^^^^

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\pyglet\window\win32\__init__.py", line 385, in switch_to
    self.context.set_current()
    ^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'set_current'
```

I get the same error regardless if I use the pyglet or new arcade run, and I did not encounter this before I upgraded arcade to the latest development version. It was previously 3.0.1.

**Comment by einarf** [comment]
> I'm getting an error that I believe is caused by this PR:
> 
> ```
>   File "C:\Users\1079235\test\src\__init__.py", line 116, in start
>     run(1/69)

Are you doing some custom run code here? You should be setting the draw and update rate instead (on the window).

I will close this issue for now. We can discuss issues with the new limitations in a new issue.

**Comment by eschan145** [comment]
That is just pyglet.app.run().

**Comment by einarf** [comment]
> That is just pyglet.app.run().

We are doing `pyglet.app.run(None)` now and simply schedule a single interval event that handles both draw and update

https://github.com/pythonarcade/arcade/blob/46ce22d28fc12e8bf1d22c6ebb87d376773b3222/arcade/application.py#L600-L601

**Comment by eschan145** [comment]
I get the same error when using the arcade run().

**Comment by einarf** [comment]
> I get the same error when using the arcade run().

Share the new stack trace please.  It can't be identical.

**Comment by eschan145** [comment]
It is identical. I think its a problem unique to my code because I can't reproduce it on any of the examples. It was working on arcade 3.0.1 and stopped working on arcade 3.0.2.

```
Traceback (most recent call last):

  File "C:\Users\1079235\test\src\__init__.py", line 120, in start
    run()

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\pyglet\app\__init__.py", line 79, in run
    event_loop.run(interval)

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\pyglet\app\base.py", line 164, in run
    timeout = self.idle()
              ^^^^^^^^^^^

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\pyglet\app\base.py", line 232, in idle
    self.clock.call_scheduled_functions(dt)

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\pyglet\clock.py", line 217, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\arcade\application.py", line 538, in _dispatch_frame
    self.draw(self._accumulated_draw_time)

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\pyglet\window\__init__.py", line 697, in draw
    self.switch_to()

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\arcade\application.py", line 1088, in switch_to
    super().switch_to()  # type: ignore # Window typed at runtime
    ^^^^^^^^^^^^^^^^^^^

  File "C:\Users\1079235\AppData\Roaming\Python\Python312\site-packages\pyglet\window\win32\__init__.py", line 385, in switch_to
    self.context.set_current()
    ^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'set_current'
```

**Comment by einarf** [comment]
You have to ensure that `interval=None` is passed to `pyglet.app.run(None)` like this. We can't use the default draw event right now until we fix the clock in pyglet somehow. There's some really nasty time sliding with interval events in the pyglet clock that causes update events to be skipped here and there causing very laggy framerates for most people.

**Comment by eschan145** [comment]
It has the same result with the same stack trace. Now, I am no expert on arcade's internals or how OpenGL works, but based on the stack trace it seems like the window is attempted to be drawn before its context is fully initialized.

The `draw_rate` or `update_rate` parameters are unchanged; the only parameters I pass to `Window` that can cause this error is title, width, and height.

**Comment by eschan145** [comment]
@einarf I have managed to reproduce the error.

The following code produces the stack trace I pasted before.

```py
import arcade

window = arcade.Window()
window.close()

window2 = arcade.Window()

arcade.run()
```

I couldn't catch it easily because one of my windows was hidden with `visible=False` in order to load some nine-patch textures on app initialization.

**Comment by einarf** [comment]
> I couldn't catch it easily because one of my windows was hidden with `visible=False` in order to load some nine-patch textures on app initialization.

It would probably be much easier to just make the ninepatches lazy?

**Comment by einarf** [comment]
@eschan145 NinePatch is lazy in dev branch now.
