### ISSUE TITLE
AttributeError: 'GDIPlusFont' object has no attribute 'hfont'

### ISSUE THREAD

**Issue by alderven** [pythonarcade/arcade#935]
Run this code:
```
import arcade

arcade.open_window(800, 600, 'Hello')
arcade.start_render()
arcade.draw_text(text='Привет!', start_x=400, start_y=300, font_size=36, color=arcade.color.RED, font_name=r'C:\propisi.ttf')
arcade.finish_render()
arcade.run()
```

Get error:
```
Traceback (most recent call last):
  File "C:/draw_text.py", line 5, in <module>
    arcade.draw_text(text='Привет!', start_x=400, start_y=300, font_size=36, color=arcade.color.RED, font_name=r'C:\propisi.ttf')
  File "C:\Program Files\Python38\lib\site-packages\arcade\text_pyglet.py", line 138, in draw_text
    label = pyglet.text.Label(
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\__init__.py", line 451, in __init__
    self.document.set_style(0, len(self.document.text), {
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\document.py", line 596, in set_style
    return super(UnformattedDocument, self).set_style(
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\document.py", line 505, in set_style
    self.dispatch_event('on_style_text', start, end, attributes)
  File "C:\Program Files\Python38\lib\site-packages\pyglet\event.py", line 415, in dispatch_event
    if handler(*args):
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1349, in on_style_text
    self._init_document()
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1319, in _init_document
    self._update()
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1233, in _update
    lines = self._get_lines()
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1210, in _get_lines
    glyphs = self._get_glyphs()
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1354, in _get_glyphs
    self._document.get_font_runs(dpi=self._dpi),
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\document.py", line 607, in get_font_runs
    ft = self.get_font(dpi=dpi)
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\document.py", line 617, in get_font
    return font.load(font_name, font_size,
  File "C:\Program Files\Python38\lib\site-packages\pyglet\font\__init__.py", line 144, in load
    font = _font_class(name, size, bold=bold, italic=italic, stretch=stretch, dpi=dpi)
  File "C:\Program Files\Python38\lib\site-packages\pyglet\font\win32.py", line 495, in __init__
    super().__init__(name, size, bold, italic, stretch, dpi)
  File "C:\Program Files\Python38\lib\site-packages\pyglet\font\win32.py", line 229, in __init__
    self.logfont = self.get_logfont(name, size, bold, italic, dpi)
  File "C:\Program Files\Python38\lib\site-packages\pyglet\font\win32.py", line 261, in get_logfont
    logfont.lfFaceName = asbytes(name)
ValueError: bytes too long (59, maximum length 32)
Exception ignored in: <function GDIPlusFont.__del__ at 0x000001762D320EE0>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\pyglet\font\win32.py", line 537, in __del__
    super(GDIPlusFont, self).__del__()
  File "C:\Program Files\Python38\lib\site-packages\pyglet\font\win32.py", line 243, in __del__
    gdi32.DeleteObject(self.hfont)
AttributeError: 'GDIPlusFont' object has no attribute 'hfont'
```

**Note:** Works OK on Arcade 2.5.7

Python: 3.8
Arcade: 2.6.0
OS: Win 10

**Comment by caffeinepills** [comment]
Just a note here on API for pyglet, the `font_name` for pyglet `Label` is the name of the font itself, not a path to the font. For a custom font you have to add the file: `pyglet.font.add_file('filename.ttf')` before the font name becomes available for use.

**Comment by einarf** [comment]
Is there anything we can do to make this a bit more user friendly?

**Comment by alderven** [comment]
> Is there anything we can do to make this a bit more user friendly?

Maybe replace error message `'GDIPlusFont' object has no attribute 'hfont'` with your comment:

> font_name for pyglet Label is the name of the font itself, not a path to the font. For a custom font you have to add the file: pyglet.font.add_file('filename.ttf') before the font name becomes available for use.
