### ISSUE TITLE
ImportError: cannot import name 'OrderedDict'

### ISSUE THREAD

**Issue by Thunder-Force** [pythonarcade/arcade#953]
## Bug Report
Using python 3.6.8 - receving error:

**"arcade\tilemap\tilemap.py", line 15, in <module>
    from typing import Any, Dict, List, Optional, OrderedDict, Tuple, Union, cast
ImportError: cannot import name 'OrderedDict'**

### Actual behavior:
Unable to execute any file with arcade library

### Expected behavior:
Able to execute file

### Steps to reproduce/example code:
pip install arcade
run any file using arcade library

## Enhancement request:
Fix import of OrderedDict

### What should be added/changed?
maybe use:
from collections import OrderedDict

### What would it help with?
Fixing the library

## Documentation request:
None

### What documentation needs to change? 
None

### Where is it located?
from typing import Any, Dict, List, Optional, OrderedDict, Tuple, Union, cast

### What is wrong with it? How can it be improved?
Fix import process.

**Comment by Cleptomania** [comment]
Yeah I’ll need to check into this, as it appears this was introduced in 3.7.2 and has since again been deprecated in 3.9, but the way that collections.OrderedDict works in 3.9+ as far as type hints are concerned has changed.

Might honestly just need to live without type hinting on the OrderedDict stuff for a while, as Tilemap and Scene both use it pretty heavily for SpriteList ordering.

If you want a quick fix though and are able to update Python this will work with 3.7+

**Comment by pvcraven** [comment]
Closing, as it appears this is 3.6 specific, and we no longer support 3.6.
